module.exports = {
    mathPlay: 'MATHPLAY',
    mathID: 'TOAN',
    mathThID: 'TOANTHCS',
    phyID: 'VATLY',
    phyThID: 'VATLITHCS',
    mathVao10ID: 'TOANVAO10',
    chemID: 'HOAHOC',
    chemThID: 'HOAHOCTHCS',
    bioID: 'SINH',
    literID: 'NGUVAN',
    literIDTHCS: 'NGUVANTHCS',
    hisID: 'LICHSU',
    geoID: 'DIALY',
    engID: 'TIENGANH',
    engTHPTID: 'ANHTHPT',
    engTHPT2: 'ANHTHPT2',
    engGRM: 'ANHGENERAL',
    engTHCS: 'ANHTHCS',
    gdcdID: 'GDCD',
}