//practice
export const FETCH_LIST_GRADE_START_ACTION = 'FETCH_LIST_GRADE_START_ACTION';
export const FETCH_LIST_GRADE_SUCCESS_ACTION = 'FETCH_LIST_GRADE_SUCCESS_ACTION';
export const FETCH_LIST_GRADE_FAILD_ACTION = 'FETCH_LIST_GRADE_FAILD_ACTION';
export const FETCH_LIST_SUBJECT_START_ACTION = 'FETCH_LIST_SUBJECT_START_ACTION';
export const FETCH_LIST_SUBJECT_SUCCESS_ACTION = 'FETCH_LIST_SUBJECT_SUCCESS_ACTION';
export const FETCH_LIST_SUBJECT_FAILD_ACTION = 'FETCH_LIST_SUBJECT_FAILD_ACTION';
export const FETCH_LIST_PROBLEM_HIERACHY_START_ACTION = 'FETCH_LIST_PROBLEM_HIERACHY_START_ACTION';
export const FETCH_LIST_PROBLEM_HIERACHY_SUCCESS_ACTION = 'FETCH_LIST_PROBLEM_HIERACHY_SUCCESS_ACTION';
export const FETCH_LIST_PROBLEM_HIERACHY_FAILD_ACTION = 'FETCH_LIST_PROBLEM_HIERACHY_FAILD_ACTION';
export const FETCH_LIST_PROBLEM_HIER_BY_ID_START_ACTION = 'FETCH_LIST_PROBLEM_HIER_BY_ID_START_ACTION';
export const FETCH_LIST_PROBLEM_HIER_BY_ID_SUCCESS_ACTION = 'FETCH_LIST_PROBLEM_HIER_BY_ID_SUCCESS_ACTION';
export const FETCH_LIST_PROBLEM_HIER_BY_ID_FAILD_ACTION = 'FETCH_LIST_PROBLEM_HIER_BY_ID_FAILD_ACTION';
export const FETCH_PRACTICE_INFO_START_ACTION = 'FETCH_PRACTICE_INFO_START_ACTION';
export const FETCH_PRACTICE_INFO_SUCCESS_ACTION = 'FETCH_PRACTICE_INFO_SUCCESS_ACTION';
export const FETCH_PRACTICE_INFO_FAILD_ACTION = 'FETCH_PRACTICE_INFO_FAILD_ACTION';
export const FETCH_PRACTICE_RECENT_START_ACTION = 'FETCH_PRACTICE_RECENT_START_ACTION';
export const FETCH_PRACTICE_RECENT_SUCCESS_ACTION = 'FETCH_PRACTICE_RECENT_SUCCESS_ACTION';
export const FETCH_PRACTICE_RECENT_FAILD_ACTION = 'FETCH_PRACTICE_RECENT_FAILD_ACTION';
export const FETCH_LIST_PRACTICE_RELATE_START_ACTION = 'FETCH_LIST_PRACTICE_RELATE_START_ACTION';
export const FETCH_LIST_PRACTICE_RELATE_SUCCESS_ACTION = 'FETCH_LIST_PRACTICE_RELATE_SUCCESS_ACTION';
export const FETCH_LIST_PRACTICE_RELATE_FAILD_ACTION = 'FETCH_LIST_PRACTICE_RELATE_FAILD_ACTION';
export const FETCH_LIST_PRACTICE_VIDEO_START_ACTION = 'FETCH_LIST_PRACTICE_VIDEO_START_ACTION';
export const FETCH_LIST_PRACTICE_VIDEO_SUCCESS_ACTION = 'FETCH_LIST_PRACTICE_VIDEO_SUCCESS_ACTION';
export const FETCH_LIST_PRACTICE_VIDEO_FAILD_ACTION = 'FETCH_LIST_PRACTICE_VIDEO_FAILD_ACTION';
export const FETCH_LIST_KIWI_SUGGEST_START_ACTION = 'FETCH_LIST_KIWI_SUGGEST_START_ACTION';
export const FETCH_LIST_KIWI_SUGGEST_SUCCESS_ACTION = 'FETCH_LIST_KIWI_SUGGEST_SUCCESS_ACTION';
export const FETCH_LIST_KIWI_SUGGEST_FAILD_ACTION = 'FETCH_LIST_KIWI_SUGGEST_FAILD_ACTION';
export const SAVE_NAVIGATOR_ACTION = 'SAVE_NAVIGATOR_ACTION';

//exam
export const FETCH_LIST_TEST_PAGE_START_ACTION = 'FETCH_LIST_TEST_PAGE_START_ACTION';
export const FETCH_LIST_TEST_PAGE_SUCCESS_ACTION = 'FETCH_LIST_TEST_PAGE_SUCCESS_ACTION';
export const FETCH_LIST_TEST_PAGE_FAILD_ACTION = 'FETCH_LIST_TEST_PAGE_FAILD_ACTION';
export const FETCH_TEST_INFO_START_ACTION = 'FETCH_TEST_INFO_START_ACTION';
export const FETCH_TEST_INFO_SUCCESS_ACTION = 'FETCH_TEST_INFO_SUCCESS_ACTION';
export const FETCH_TEST_INFO_FAILD_ACTION = 'FETCH_TEST_INFO_FAILD_ACTION';

export const FETCH_TEST_DONE_START_ACTION = 'FETCH_TEST_DONE_START_ACTION';
export const FETCH_TEST_DONE_SUCCESS_ACTION = 'FETCH_TEST_DONE_SUCCESS_ACTION';
export const FETCH_TEST_DONE_FAILD_ACTION = 'FETCH_TEST_DONE_FAILD_ACTION';

//auth user account parent
export const FETCH_PROFILE_UPDATE_START_ACTION = 'FETCH_PROFILE_UPDATE_START_ACTION';
export const FETCH_PROFILE_UPDATE_SUCCESS_ACTION = 'FETCH_PROFILE_UPDATE_SUCCESS_ACTION';
export const FETCH_PROFILE_UPDATE_FAILD_ACTION = 'FETCH_PROFILE_UPDATE_FAILD_ACTION';
export const FETCH_LIST_CHILD_START_ACTION = 'FETCH_LIST_CHILD_START_ACTION';
export const FETCH_LIST_CHILD_SUCCESS_ACTION = 'FETCH_LIST_CHILD_SUCCESS_ACTION';
export const FETCH_LIST_CHILD_FAILD_ACTION = 'FETCH_LIST_CHILD_FAILD_ACTION';
export const FETCH_ADD_CHILD_START_ACTION = 'FETCH_ADD_CHILD_START_ACTION';
export const FETCH_ADD_CHILD_SUCCESS_ACTION = 'FETCH_ADD_CHILD_SUCCESS_ACTION';
export const FETCH_ADD_CHILD_FAILD_ACTION = 'FETCH_ADD_CHILD_FAILD_ACTION';
export const FETCH_UPDATE_CHILD_START_ACTION = 'FETCH_UPDATE_CHILD_START_ACTION';
export const FETCH_UPDATE_CHILD_SUCCESS_ACTION = 'FETCH_UPDATE_CHILD_SUCCESS_ACTION';
export const FETCH_UPDATE_CHILD_FAILD_ACTION = 'FETCH_UPDATE_CHILD_FAILD_ACTION';
export const FETCH_REMOVE_CHILD_START_ACTION = 'FETCH_REMOVE_CHILD_START_ACTION';
export const FETCH_REMOVE_CHILD_SUCCESS_ACTION = 'FETCH_REMOVE_CHILD_SUCCESS_ACTION';
export const FETCH_REMOVE_CHILD_FAILD_ACTION = 'FETCH_REMOVE_CHILD_FAILD_ACTION';
export const MAKE_REQUEST_PROFILE_ACTION = 'MAKE_REQUEST_PROFILE_ACTION';

//parent
export const MAKE_REQUEST_PROFILE_PARENT_ACTION = 'MAKE_REQUEST_PROFILE_PARENT_ACTION';
export const FETCH_FLASHCARD_KNOWLEAGE_START_ACTION = 'FETCH_FLASHCARD_KNOWLEAGE_START_ACTION';
export const FETCH_FLASHCARD_KNOWLEAGE_SUCCESS_ACTION = 'FETCH_FLASHCARD_KNOWLEAGE_SUCCESS_ACTION';
export const FETCH_FLASHCARD_KNOWLEAGE_FAILD_ACTION = 'FETCH_FLASHCARD_KNOWLEAGE_FAILD_ACTION';
export const FETCH_NOTIFY_PARENT_START_ACTION = 'FETCH_NOTIFY_PARENT_START_ACTION';
export const FETCH_NOTIFY_PARENT_SUCCESS_ACTION = 'FETCH_NOTIFY_PARENT_SUCCESS_ACTION';
export const FETCH_NOTIFY_PARENT_FAILD_ACTION = 'FETCH_NOTIFY_PARENT_FAILD_ACTION';
export const FETCH_PATHWAY_ACTION = 'FETCH_PATHWAY_ACTION';
export const FETCH_PATHWAY_SUCCESS_ACTION = 'FETCH_PATHWAY_SUCCESS_ACTION';
export const FETCH_PATHWAY_FAILED_ACTION = 'FETCH_PATHWAY_FAILED_ACTION';
export const SAVE_DATA_PROPLEMS_ID_UPDATE_PATHWAY_ACTION = 'SAVE_DATA_PROPLEMS_ID_UPDATE_PATHWAY_ACTION';
export const GET_EXERCISE_START_ACTION= 'GET_EXERCISE_START_ACTION';

export const GET_EXERCISE_NOT_DONE_SUCCESS_ACTION= 'GET_EXERCISE_NOT_DONE_SUCCESS_ACTION';
export const GET_EXERCISE_NOT_DONE_FAILD_ACTION= 'GET_EXERCISE_NOT_DONE_FAILD_ACTION';
export const GET_EXERCISE_DONE_SUCCESS_ACTION= 'GET_EXERCISE_DONE_SUCCESS_ACTION';
export const GET_EXERCISE_DONE_FAILD_ACTION= 'GET_EXERCISE_DONE_FAILD_ACTION';

export const GET_EXERCISE_ASSIGN_START_ACTION= 'GET_EXERCISE_ASSIGN_START_ACTION';
export const GET_EXERCISE_ASSIGN_SUCCESS_ACTION= 'GET_EXERCISE_ASSIGN_SUCCESS_ACTION';
export const GET_EXERCISE_ASSIGN_FAILD_ACTION= 'GET_EXERCISE_ASSIGN_FAILD_ACTION';
export const GET_LESSON_FOLLOW_BY_PACKAGE_START_ACTION= 'GET_LESSON_FOLLOW_BY_PACKAGE_START_ACTION';
export const GET_LESSON_FOLLOW_BY_PACKAGE_SUCCESS_ACTION= 'GET_LESSON_FOLLOW_BY_PACKAGE_SUCCESS_ACTION';
export const GET_LESSON_FOLLOW_BY_PACKAGE_FAILD_ACTION= 'GET_LESSON_FOLLOW_BY_PACKAGE_FAILD_ACTION';
export const GET_EXERCISE_DETAIL_START_ACTION= 'GET_EXERCISE_DETAIL_START_ACTION';
export const GET_EXERCISE_DETAIL_SUCCESS_ACTION= 'GET_EXERCISE_DETAIL_SUCCESS_ACTION';
export const GET_EXERCISE_DETAIL_FAILD_ACTION= 'GET_EXERCISE_DETAIL_FAILD_ACTION';

export const GET_CHART_DETAIL_START_ACTION = 'GET_CHART_DETAIL_START_ACTION';
export const GET_CHART_DETAIL_SUCCESS_ACTION = 'GET_CHART_DETAIL_SUCCESS_ACTION';
export const GET_CHART_DETAIL_FAILED_ACTION = 'GET_CHART_DETAIL_FAILED_ACTION';

export const GET_FETCH_NOTI_START_ACTION = 'GET_FETCH_NOTI_START_ACTION';
export const GET_FETCH_NOTI_SUCCESS_ACTION = 'GET_FETCH_NOTI_SUCCESS_ACTION';
export const GET_FETCH_NOTI_FAILED_ACTION = 'GET_FETCH_NOTI_FAILED_ACTION';

export const FETCH_CHILD_MISSONS_START_ACTION = 'FETCH_CHILD_MISSONS_START_ACTION';
export const FETCH_CHILD_MISSONS_SUCCESS_ACTION = 'FETCH_CHILD_MISSONS_SUCCESS_ACTION';
export const FETCH_CHILD_MISSONS_FAILED_ACTION = 'FETCH_CHILD_MISSONS_FAILED_ACTION';

//package
export const FETCH_PACKAGE_LIST_START_ACTION = 'FETCH_PACKAGE_LIST_START_ACTION';
export const FETCH_PACKAGE_LIST_SUCCESS_ACTION = 'FETCH_PACKAGE_LIST_SUCCESS_ACTION';
export const FETCH_PACKAGE_LIST_FAILD_ACTION = 'FETCH_PACKAGE_LIST_FAILD_ACTION';

export const FETCH_PACKAGE_LIST_BYID_START_ACTION = 'FETCH_PACKAGE_LIST_BYID_START_ACTION';
export const FETCH_PACKAGE_LIST_BYID_SUCCESS_ACTION = 'FETCH_PACKAGE_LIST_BYID_SUCCESS_ACTION';
export const FETCH_PACKAGE_LIST_BYID_FAILD_ACTION = 'FETCH_PACKAGE_LIST_BYID_FAILD_ACTION';

export const FETCH_PACKAGE_INFO_START_ACTION = 'FETCH_PACKAGE_INFO_START_ACTION';
export const FETCH_PACKAGE_INFO_SUCCESS_ACTION = 'FETCH_PACKAGE_INFO_SUCCESS_ACTION';
export const FETCH_PACKAGE_INFO_FAILD_ACTION = 'FETCH_PACKAGE_INFO_FAILD_ACTION';

export const ADD_PACKAGE_LIST_BYID_START_ACTION = 'ADD_PACKAGE_LIST_BYID_START_ACTION';
export const ADD_PACKAGE_LIST_BYID_SUCCESS_ACTION = 'ADD_PACKAGE_LIST_BYID_SUCCESS_ACTION';
export const ADD_PACKAGE_LIST_BYID_FAILD_ACTION = 'ADD_PACKAGE_LIST_BYID_FAILD_ACTION';

export const DEL_PACKAGE_LIST_BYID_START_ACTION = 'DEL_PACKAGE_LIST_BYID_START_ACTION';
export const DEL_PACKAGE_LIST_BYID_SUCCESS_ACTION = 'DEL_PACKAGE_LIST_BYID_SUCCESS_ACTION';
export const DEL_PACKAGE_LIST_BYID_FAILD_ACTION = 'DEL_PACKAGE_LIST_BYID_FAILD_ACTION';

//common
export const CREATE_FIRST_CHILD_ACTION = 'CREATE_FIRST_CHILD_ACTION';
export const FETCH_MISSON_FROM_CHILD_START_ACTION = 'FETCH_MISSON_FROM_CHILD_START_ACTION';
export const FETCH_MISSON_FROM_CHILD_SUCCESS_ACTION = 'FETCH_MISSON_FROM_CHILD_SUCCESS_ACTION';
export const FETCH_MISSON_FROM_CHILD_FAILED_ACTION = 'FETCH_MISSON_FROM_CHILD_FAILED_ACTION';
export const FETCH_SAVE_PARENT_AVATARSTART_ACTION = 'FETCH_SAVE_PARENT_AVATARSTART_ACTION';



