const dataFlatlist = [
    {
        key: 1,
        index: 1,
    },
    {
        key: 2,
        index: 2,
    },
    {
        key: 3,
        index: 3,
    },
    {
        key: 4,
        index: 4,
    },
    {
        key: 5,
        index: 5,
    },
    {
        key: 6,
        index: 6,
    },
    {
        key: 7,
        index: 7,
    },
    {
        key: 8,
        index: 8,
    },
    {
        key: 9,
        index: 9,
    },
    {
        key: 10,
        index: 10,
    },
    {
        key: 11,
        index: 11,
    },
    {
        key: 12,
        index: 12,
    }
];

const dataGrade = [
    { label: 'Lớp 1', value: 'C1' },
    { label: 'Lớp 2', value: 'C2' },
    { label: 'Lớp 3', value: 'C3' }
];

const dataGender = [
    { label: 'Nam', value: 'NAM' },
    { label: 'Nữ', value: 'NU' }
];

const dataParent = [
    { label: 'Cha', value: 'NAM' },
    { label: 'Mẹ', value: 'NU' }
];

const dataSwipper = [
    [
        {
            id: 1,
            name: 'dsadsa'
        },
        {
            id: 2,
            name: 'dsadsa'
        },
        {
            id: 3,
            name: 'dsadsa'
        },
        {
            id: 4,
            name: 'dsadsa'
        }
    ],
    [
        {
            id: 5,
            name: 'dsadsa'
        },
        {
            id: 6,
            name: 'dsadsa'
        },
        {
            id: 7,
            name: 'dsadsa'
        },
        {
            id: 8,
            name: 'dsadsa'
        }
    ],
    [
        {
            id: 9,
            name: 'dsadsa'
        },
        {
            id: 10,
            name: 'dsadsa'
        },
        {
            id: 11,
            name: 'dsadsa'
        },
        {
            id: 12,
            name: 'dsadsa'
        }
    ]
]

const datalistProblemHierachy = [
    {
        codeKnowledge: "",
        gradeId: "",
        id: "",
        name: "",
        subjectId: "",
        totalProblem: 0,
        totalProblemLevel0: 0,
        totalProblemLevel1: 0,
        totalProblemLevel2: 0,
        totalProblemLevel3: 0
    },
    {
        codeKnowledge: "",
        gradeId: "",
        id: "",
        name: "",
        subjectId: "",
        totalProblem: 0,
        totalProblemLevel0: 0,
        totalProblemLevel1: 0,
        totalProblemLevel2: 0,
        totalProblemLevel3: 0
    },
    {
        codeKnowledge: "",
        gradeId: "",
        id: "",
        name: "",
        subjectId: "",
        totalProblem: 0,
        totalProblemLevel0: 0,
        totalProblemLevel1: 0,
        totalProblemLevel2: 0,
        totalProblemLevel3: 0
    },
    {
        codeKnowledge: "",
        gradeId: "",
        id: "",
        name: "",
        subjectId: "",
        totalProblem: 0,
        totalProblemLevel0: 0,
        totalProblemLevel1: 0,
        totalProblemLevel2: 0,
        totalProblemLevel3: 0
    }
]


const datalistProblemHierachyExerice = [
    {
        levelPractice: 0,
        subjectId: "",
        title: " ",
    },
    {
        levelPractice: 0,
        subjectId: "",
        title: " ",
    },
    {
        levelPractice: 0,
        subjectId: "",
        title: " ",
    },
    {
        levelPractice: 0,
        subjectId: "",
        title: " ",
    },
    {
        levelPractice: 0,
        subjectId: "",
        title: " ",
    },
    {
        levelPractice: 0,
        subjectId: "",
        title: " ",
    },
    {
        levelPractice: 0,
        subjectId: "",
        title: " ",
    },
    {
        levelPractice: 0,
        subjectId: "",
        title: " ",
    },
    {
        levelPractice: 0,
        subjectId: "",
        title: " ",
    },
    {
        levelPractice: 0,
        subjectId: "",
        title: " ",
    },
    {
        levelPractice: 0,
        subjectId: "",
        title: " ",
    },
    {
        levelPractice: 0,
        subjectId: "",
        title: " ",
    }
]

const listTest = [
    {
        id: 1,
        title: ' ',
    },
    {
        id: 2,
        title: ' ',
    },
    {
        id: 3,
        title: ' ',
    },
    {
        id: 4,
        title: ' ',
    },
    {
        id: 5,
        title: ' ',
    }
]

const dataProgramC1 = [
    { type: 'head', title: 'A. Các số tự nhiên từ 0 - 10' },
    { type: 'item', title: 'A.1   Đếm các số từ 1 - 10' },
    { type: 'item', title: 'A.2   Đọc, viết các số từ 1 - 10' },
    { type: 'item', title: 'A.2   Số 0' },
    { type: 'head', title: 'B. So sánh các số từ 0 - 10' },
    { type: 'item', title: 'B.1   Nhiều hơn, ít hơn, đủ' },
    { type: 'item', title: 'B.2   So sánh 2 số từ 0 - 10 qua hình ảnh' },
    { type: 'item', title: 'B.3   So sánh 2 số từ 0 - 10' },
    { type: 'head', title: 'C. Phép cộng trong phạm vi 10' },
    { type: 'item', title: 'C.1   Giới thiệu phép cộng, phép trừ' },
    { type: 'item', title: 'C.2   Phép cộng bằng hình ảnh trong phạm vi 10' },
    { type: 'item', title: 'C.3   cộng trong phạm vi 10' },
    { type: 'item', title: 'C.4   Phép cộng nhiều số trong phạm vi 10' },
    { type: 'item', title: 'C.5   Phép cộng đến 10 trong bài toán có lời văn' },
    { type: 'head', title: 'D. Phép trừ trong phạm vi 10' },
    { type: 'item', title: 'D.1   Phép trừ bằng hình ảnh' },
    { type: 'item', title: 'D.2   Phép trừ trong phạm vi 10' },
    { type: 'item', title: 'D.3   Phép trừ nhiều số trong phạm vi 10' },
    { type: 'item', title: 'D.4   Phép cộng, trừ nhiều số trong phạm vi 10' },
    { type: 'item', title: 'D.5   Phép trừ phạm vi 10 trong bài toán có lời văn' },
    { type: 'item', title: 'D.6   Bảng cộng, trừ trong phạm vi 10' },
    { type: 'head', title: 'E.Các số trong phạm vi 100' },
    { type: 'item', title: 'E.1   Một chục. Tia số' },
    { type: 'item', title: 'E.2   Đếm các số trong phạm vi 20' },
    { type: 'item', title: 'E.3   Đọc, viết các số trong phạm vi 20' },
    { type: 'item', title: 'E.4   Đếm theo chục và đơn vị' },
    { type: 'item', title: 'E.5   Các số tròn chục' },
    { type: 'item', title: 'E.6   Đếm các số có 2 chữ số' },
    { type: 'item', title: 'E.7   Đọc, viết các số có 2 chữ số' },
    { type: 'head', title: 'F. So sánh các số trong phạm vi 100' },
    { type: 'item', title: 'F.1   So sánh các số có 2 chữ số qua hình ảnh' },
    { type: 'item', title: 'F.2   So sánh các số có 2 chữ số' },
    { type: 'head', title: 'G. Phép cộng trong phạm vi 100' },
    { type: 'item', title: 'G.1   Cộng các số tròn chục' },
    { type: 'item', title: 'G.2   Cộng số có 2 chữ số với số có 1 chữ số (không nhớ)' },
    { type: 'item', title: 'G.3   Cộng số có 2 chữ số với số có 2 chữ số (không nhớ)' },
    { type: 'item', title: 'G.4   Phép cộng nhiều số trong phạm vi 100 (không nhớ)' },
    { type: 'item', title: 'G.5   Phép cộng trong bài toán có lời văn' },
    { type: 'head', title: 'H. Phép trừ trong phạm vi 100' },
    { type: 'item', title: 'H.1   Trừ các số tròn chục' },
    { type: 'item', title: 'H.2   Trừ số có 2 chữ số cho số có 1 chữ số (không nhớ)' },
    { type: 'item', title: 'H.3   Trừ số có 2 chữ số cho số có 2 chữ số (không nhớ)' },
    { type: 'item', title: 'H.4   Phép trừ nhiều số trong phạm vi 100 (không nhớ)' },
    { type: 'item', title: 'H.5   Phép cộng, trừ nhiều số trong phạm vi 100' },
    { type: 'item', title: 'H.6   Phép trừ trong bài toán có lời văn' },
    { type: 'head', title: 'I. Hình phẳng và hình khối' },
    { type: 'item', title: 'I.1   Hình phẳng và hình khối' },
    { type: 'item', title: 'I.2   Hình vuông' },
    { type: 'item', title: 'I.3   Hình tròn' },
    { type: 'item', title: 'I.4   Hình tam giác' },
    { type: 'item', title: 'I.5   Hình chữ nhật' },
    { type: 'item', title: 'I.6   Hình vuông, hình tròn, hình tam giác, hình chữ nhật' },
    { type: 'item', title: 'I.7   Khối lập phương' },
    { type: 'item', title: 'I.8   Khối hộp chữ nhật' },
    { type: 'item', title: 'I.9   Bài toán ghép hình' },
    { type: 'head', title: 'K. Đo lường' },
    { type: 'item', title: 'K.1   Dài hơn, ngắn hơn' },
    { type: 'item', title: 'K.2   Thực hành đo độ dài' },
    { type: 'item', title: 'K.3   Xăng-ti-mét' },
    { type: 'item', title: 'K.4   Đo độ dài bằng thước thẳng' },
    { type: 'item', title: 'K.5   Bài toán thực tế về đo độ dài' },
    { type: 'head', title: 'L. Điểm, đoạn thẳng' },
    { type: 'item', title: 'L.1   Điểm, đoạn thẳng' },
    { type: 'item', title: 'L.2   Điểm ở trong, ở ngoài một hình' },
    { type: 'item', title: 'L.3   Đo độ dài đoạn thẳng cho trước' },
    { type: 'item', title: 'L.4   Vẽ độ dài đoạn thẳng cho trước' },
    { type: 'head', title: 'M. Thời gian' },
    { type: 'item', title: 'M.1   Các ngày trong tuần lễ' },
    { type: 'item', title: 'M.2   Thực hành xem lịch' },
    { type: 'item', title: 'M.3   Bài toán thực tế về xem lịch' },
    { type: 'item', title: 'M.4   Đồng hồ' },
    { type: 'item', title: 'M.5   Thực hành xem đồng hồ' },
    { type: 'item', title: 'M.6   Bài toán thực tế về đồng hồ' },
    { type: 'head', title: 'N. Vị trí' },
    { type: 'item', title: 'N.1   Vị trí: trên - dưới' },
    { type: 'item', title: 'N.2   Vị trí: trái - ở giữa - phải' },
    { type: 'item', title: 'N.3   Vị trí: trước - ở giữa - sau' }
];

const dataProgramC2 = [
    { type: 'head', title: 'A. Phép cộng có nhớ pv 100' },
    { type: 'item', title: 'A.1    Số hạng - tổng' },
    { type: 'item', title: 'A.2    Phép cộng có tổng bằng 10' },
    { type: 'item', title: 'A.3    Phép tính có tổng là số tròn chục' },
    { type: 'item', title: 'A.4    Phép cộng có nhớ trong phạm vi 20' },
    { type: 'item', title: 'A.5    Cộng số có 2 chữ số với số có 1 chữ số trong phạm vi 100 (có nhớ)' },
    { type: 'item', title: 'A.6    Cộng số có 2 chữ số với số có 2 chữ số trong phạm vi 100 (có nhớ)' },
    { type: 'item', title: 'A.7    Bảng cộng' },
    { type: 'item', title: 'A.8    Phép cộng có tổng bằng 100' },
    { type: 'item', title: 'A.9    Phép cộng nhiều số có nhớ trong phạm vi 100' },
    { type: 'head', title: 'B. Phép trừ có nhớ pv 100' },
    { type: 'item', title: 'B.1    Số bị trừ - Số trừ - Hiệu' },
    { type: 'item', title: 'B.2    Số tròn chục trừ đi một số' },
    { type: 'item', title: 'B.3    Phép trừ có nhớ trong phạm vi 20' },
    { type: 'item', title: 'B.4    Trừ số có 2 chữ số cho số có 1 chữ số trong phạm vi 100 (có nhớ)' },
    { type: 'item', title: 'B.5    Trừ số có 2 chữ số cho số có 2 chữ số trong phạm vi 100 (có nhớ)' },
    { type: 'item', title: 'B.6    Bảng trừ' },
    { type: 'item', title: 'B.7    100 trừ đi một số' },
    { type: 'item', title: 'B.8    Phép trừ nhiều số có nhớ trong phạm vi 100' },
    { type: 'item', title: 'B.9    Phép cộng, trừ nhiều số có nhớ trong phạm vi 100' },
    { type: 'head', title: 'C. Giải toán có lời văn' },
    { type: 'item', title: 'C.1    Bài toán về nhiều hơn' },
    { type: 'item', title: 'C.2   Bài toán về ít hơn' },
    { type: 'item', title: 'C.3   Bài toán có lời văn (phép cộng)' },
    { type: 'item', title: 'C.4   toán có lời văn (phép trừ)' },
    { type: 'head', title: 'D. Phép nhân' },
    { type: 'item', title: 'D.1    Tổng của nhiều số' },
    { type: 'item', title: 'D.2    Phép nhân' },
    { type: 'item', title: 'D.3    Thừa số, tích' },
    { type: 'item', title: 'D.4    Bảng nhân 2' },
    { type: 'item', title: 'D.5    Bảng nhân 3' },
    { type: 'item', title: 'D.6    Bảng nhân 4' },
    { type: 'item', title: 'D.7    Bảng nhân 5' },
    { type: 'item', title: 'D.8    Số 0 và số 1 trong phép nhân' },
    { type: 'item', title: 'D.9    Bài toán có lời văn (phép nhân)' },
    { type: 'head', title: 'E. Phép chia' },
    { type: 'item', title: 'E.1    Phép chia' },
    { type: 'item', title: 'E.2    Số bị chia, Số chia, Thương' },
    { type: 'item', title: 'E.3    Bảng chia 2' },
    { type: 'item', title: 'E.4    Bảng chia 3' },
    { type: 'item', title: 'E.5    Bảng chia 4' },
    { type: 'item', title: 'E.6    Bảng chia 5' },
    { type: 'item', title: 'E.7    Số 0 và số 1 trong phép chia' },
    { type: 'item', title: 'E.8    Bài toán có lời văn (phép chia)' },
    { type: 'head', title: 'F. Phân số' },
    { type: 'item', title: 'F.1    Các phần bằng nhau của một hình' },
    { type: 'item', title: 'F.2    Nhận biết phân số bằng hình ảnh' },
    { type: 'item', title: 'F.3    Đọc, viết phân số' },
    { type: 'item', title: 'F.4    Tìm giá trị phân số của một số bằng hình ảnh' },
    { type: 'head', title: 'G. Bài toán tìm x' },
    { type: 'item', title: 'G.1    Tìm một số hạng trong một tổng' },
    { type: 'item', title: 'G.2    Tìm số bị trừ' },
    { type: 'item', title: 'G.3    Tìm số trừ' },
    { type: 'item', title: 'G.4    Tìm một thừa số của phép nhân' },
    { type: 'item', title: 'G.5    Tìm số bị chia' },
    { type: 'head', title: 'H. Các số trong phạm vi 1000' },
    { type: 'item', title: 'H.1    Đơn vị, chục, trăm, nghìn' },
    { type: 'item', title: 'H.2    Ước lượng số lượng đồ vật' },
    { type: 'item', title: 'H.3    So sánh các số tròn trăm' },
    { type: 'item', title: 'H.4    Các số tròn chục từ 110 - 200' },
    { type: 'item', title: 'H.5    Đếm, đọc, viết các số có 3 chữ số' },
    { type: 'item', title: 'H.6    Viết các số thành tổng của trăm, chục, đơn vị' },
    { type: 'item', title: 'H.7    Tia số' },
    { type: 'item', title: 'H.8    Số liền trước, số liền sau' },
    { type: 'item', title: 'H.9    So sánh các số có 3 chữ số' },
    { type: 'item', title: 'H.10    Sắp xếp các số theo thứ tự' },
    { type: 'item', title: 'H.11    Số lớn nhất, số bé nhất' },
    { type: 'head', title: 'I. Đo lường' },
    { type: 'item', title: 'I.1    Đề-xi-mét' },
    { type: 'item', title: 'I.2    Mét' },
    { type: 'item', title: 'I.3    Ki-lô-mét' },
    { type: 'item', title: 'I.4    Mi-li-mét' },
    { type: 'item', title: 'I.5    Đổi đơn vị đo độ dài' },
    { type: 'item', title: 'I.6    Ước lượng số đo' },
    { type: 'item', title: 'I.7    Nặng hơn, nhẹ hơn' },
    { type: 'item', title: 'I.8    Ki-lô-gam' },
    { type: 'item', title: 'I.9    Sử dụng một số loại cân thông dụng' },
    { type: 'item', title: 'I.10    Bài toán thực tế về khối lượng' },
    { type: 'item', title: 'I.11    Lít' },
    { type: 'item', title: 'I.12    Bài toán thực tế về dung tích' },
    { type: 'item', title: 'I.13    Ngày, giờ' },
    { type: 'item', title: 'I.14    Giờ lẻ 15 phút; giờ rưỡi' },
    { type: 'item', title: 'I.15    Bài toán liên quan đến đồng hồ' },
    { type: 'item', title: 'I.16    Ngày tháng' },
    { type: 'item', title: 'I.17    Thực hành xem lịch' },
    { type: 'item', title: 'I.18    Tiền Việt Nam' },
    { type: 'head', title: 'K. Hình học' },
    { type: 'item', title: 'K.1    Hình chữ nhật, hình tứ giác' },
    { type: 'item', title: 'K.2    Điểm, đoạn thẳng' },
    { type: 'item', title: 'K.3    Đo độ dài đoạn thẳng cho trước' },
    { type: 'item', title: 'K.4    Vẽ độ dài đoạn thẳng cho trước' },
    { type: 'item', title: 'K.5    Đường thẳng' },
    { type: 'item', title: 'K.6    Ba điểm thẳng hàng' },
    { type: 'item', title: 'K.7    Đường gấp khúc' },
    { type: 'item', title: 'K.8    Độ dài đường gấp khúc' },
    { type: 'item', title: 'K.9    Chu vi hình tam giác, hình tứ giác' },
    { type: 'item', title: 'K.10    Khối trụ, khối cầu' },
    { type: 'item', title: 'K.11    Ghép hình' },
    { type: 'head', title: 'L. Xác suất thống kê' },
    { type: 'item', title: 'L.1    Làm quen với bảng số liệu thống kê' },
    { type: 'item', title: 'L.2    Phân tích biểu đồ tranh' },
    { type: 'item', title: 'L.3    Nhận xét biểu đồ tranh' },
    { type: 'item', title: 'L.4    Xác suất' },
    { type: 'head', title: 'M. Phép cộng, trừ trong phạm vi 1000' },
    { type: 'item', title: 'M.1   Cộng trừ các số có 3 chữ số (không nhớ) ' },
    { type: 'item', title: 'M.2   Cộng các số có 3 chữ số (nhớ 1 lần)' },
    { type: 'item', title: 'M.3   Trừ các số có 3 chữ số (nhớ 1 lần)' },
    { type: 'item', title: 'M.4   Cộng trừ số tròn chục' },
    { type: 'item', title: 'M.5   Cộng trừ số tròn trăm' }
];

const dataProgramC3 = [
    { type: 'head', title: 'A. Cộng, trừ các số có 3 chữ số' },
    { type: 'item', title: 'A.1   Cộng trừ các số có 3 chữ số (không nhớ)' },
    { type: 'item', title: 'A.2   Cộng các số có 3 chữ số (nhớ 1 lần)' },
    { type: 'item', title: 'A.3   Trừ các số có 3 chữ số (nhớ 1 lần)' },
    { type: 'item', title: 'A.4   Tính chất giao hoán của phép cộng ' },
    { type: 'item', title: 'A.5   Tính chất kết hợp của phép cộng' },
    { type: 'item', title: 'A.6   Mối quan hệ giữa phép cộng và phép trừ' },
    { type: 'head', title: 'B. Phép nhân và phép chia trong phạm vi 1000' },
    { type: 'item', title: 'B.1   Bảng nhân 6' },
    { type: 'item', title: 'B.2   Bảng chia 6' },
    { type: 'item', title: 'B.3   Bảng nhân 7' },
    { type: 'item', title: 'B.4   Bảng chia 7' },
    { type: 'item', title: 'B.5   Bảng nhân 8' },
    { type: 'item', title: 'B.6   Bảng chia 8' },
    { type: 'item', title: 'B.7   Bảng nhân 9' },
    { type: 'item', title: 'B.8   Bảng chia 9' },
    { type: 'item', title: 'B.9   Giới thiệu bảng nhân' },
    { type: 'item', title: 'B.10  Giới thiệu bảng chia' },
    { type: 'item', title: 'B.11  Nhân số có 2 chữ số với số có 1 chữ số (không nhớ)' },
    { type: 'item', title: 'B.12  Nhân số có 2 chữ số với số có 1 chữ số (có nhớ)' },
    { type: 'item', title: 'B.13  Nhân số có 3 chữ số với số có 1 chữ số (không nhớ)' },
    { type: 'item', title: 'B.14  Nhân số có 3 chữ số với số có 1 chữ số (có nhớ)' },
    { type: 'item', title: 'B.15  Phép chia hết, phép chia có dư' },
    { type: 'item', title: 'B.16  Chia số có 2 chữ số cho số có 1 chữ số (chia hết)' },
    { type: 'item', title: 'B.17  Chia số có 2 chữ số cho số có 1 chữ số (có dư)' },
    { type: 'item', title: 'B.18  Chia số có 3 chữ số cho số có 1 chữ số (chia hết)' },
    { type: 'item', title: 'B.19  Chia số có 3 chữ số cho số có 1 chữ số (có dư)' },
    { type: 'item', title: 'B.20  Tính chất giao hoán của phép nhân' },
    { type: 'item', title: 'B.21  Tính chất kết hợp của phép nhân' },
    { type: 'item', title: 'B.22  Mối quan hệ của phép nhân và phép chia trong thực hành tính' },
    { type: 'head', title: 'C. Biểu thức' },
    { type: 'item', title: 'C.1   Làm quen với biểu thức' },
    { type: 'item', title: 'C.2   Biểu thức đơn giản' },
    { type: 'item', title: 'C.3   Biểu thức gồm nhiều phép tính' },
    { type: 'item', title: 'C.4   Biểu thức chứa dấu ngoặc' },
    { type: 'item', title: 'C.5   Tìm một số hạng trong một tổng' },
    { type: 'item', title: 'C.6   Tìm số bị trừ' },
    { type: 'item', title: 'C.7   Tìm số trừ' },
    { type: 'item', title: 'C.8   Tìm một thừa số của phép nhân' },
    { type: 'item', title: 'C.9   Tìm số bị chia' },
    { type: 'item', title: 'C.10   Tìm số chia' },
    { type: 'head', title: 'D. Phân số' },
    { type: 'item', title: 'D.1   Các phần bằng nhau của một hình.' },
    { type: 'item', title: 'D.2   Nhận biết phân số bằng hình ảnh.' },
    { type: 'item', title: 'D.3   Đọc, viết phân số.' },
    { type: 'item', title: 'D.4   Tìm giá trị phân số của một số bằng hình ảnh.' },
    { type: 'item', title: 'D.5   Tìm giá trị của phân số của một số.' },
    { type: 'head', title: 'E. Giải toán có lời văn' },
    { type: 'item', title: 'E.1   Tìm 1 trong các phần bằng nhau của 1 số' },
    { type: 'item', title: 'E.2   Gấp 1 số lên nhiều lần' },
    { type: 'item', title: 'E.3   Giảm đi 1 số lần' },
    { type: 'item', title: 'E.4   Bài toán giải bằng hai phép tính' },
    { type: 'item', title: 'E.5   So sánh số lớn gấp mấy lần số bé' },
    { type: 'item', title: 'E.6   So sánh số bé bằng một phần mấy số lớn' },
    { type: 'item', title: 'E.7   Bài toán liên quan đến rút về đơn vị' },
    { type: 'head', title: 'F. Các số đến 10 000' },
    { type: 'item', title: 'F.1   Đọc, viết các số có 4 chữ số' },
    { type: 'item', title: 'F.2  Cấu tạo thập phân của một số' },
    { type: 'item', title: 'F.3  Số tròn nghìn' },
    { type: 'item', title: 'F.4  So sánh các số trong phạm vi 10000' },
    { type: 'item', title: 'F.5  Xác định số lớn nhất, số bé nhất' },
    { type: 'item', title: 'F.6  Sắp xếp các số theo thứ tự' },
    { type: 'item', title: 'F.7  Làm quen với chữ số La Mã' },
    { type: 'item', title: 'F.8  Làm tròn số' },
    { type: 'item', title: 'F.9  Phép cộng các số trong phạm vi 10000' },
    { type: 'item', title: 'F.10  Phép trừ các số trong phạm vi 10000' },
    { type: 'item', title: 'F.11  Nhân số có 4 chữ số với số có 1 chữ số (không nhớ)' },
    { type: 'item', title: 'F.12  Nhân số có 4 chữ số với số có 1 chữ số (có nhớ)' },
    { type: 'item', title: 'F.13  Chia số có 4 chữ số với số có 1 chữ số (chia hết)' },
    { type: 'item', title: 'F.14  Chia số có 4 chữ số với số có 1 chữ số (có dư)' },
    { type: 'head', title: 'G. Các số đến 100 000' },
    { type: 'item', title: 'G.1   Đọc, viết các số có 5 chữ số' },
    { type: 'item', title: 'G.2   Số tròn mười nghìn' },
    { type: 'item', title: 'G.3   So sánh các số trong phạm vi 100000' },
    { type: 'item', title: 'G.4   Phép cộng các số trong phạm vi 100000' },
    { type: 'item', title: 'G.5   Phép trừ các số trong phạm vi 100000' },
    { type: 'item', title: 'G.6   Nhân số có 5 chữ số với số có 1 chữ số (không nhớ)' },
    { type: 'item', title: 'G.7   Nhân số có 5 chữ số với số có 1 chữ số (có nhớ)' },
    { type: 'item', title: 'G.8   Chia số có 5 chữ số với số có 1 chữ số (chia hết)' },
    { type: 'item', title: 'G.9   Chia số có 5 chữ số với số có 1 chữ số (có dư)' },
    { type: 'head', title: 'H. Hình học trực quan' },
    { type: 'item', title: 'H.1   Điểm ở giữa - Trung điểm của đoạn thẳng' },
    { type: 'item', title: 'H.2   Góc vuông, góc không vuông' },
    { type: 'item', title: 'H.3   Thực hành vẽ góc vuông' },
    { type: 'item', title: 'H.4   Thực hành nhận biết góc vuông bằng ê ke' },
    { type: 'item', title: 'H.5   Cạnh, góc' },
    { type: 'item', title: 'H.6   Tam giác, tứ giác' },
    { type: 'item', title: 'H.7   Hình chữ nhật' },
    { type: 'item', title: 'H.8   Thực hành vẽ hình chữ nhật' },
    { type: 'item', title: 'H.9   Hình vuông' },
    { type: 'item', title: 'H.10   Thực hành vẽ hình vuông' },
    { type: 'item', title: 'H.11   Hình tròn, tâm, đường kính, bán kính' },
    { type: 'item', title: 'H.12   Vẽ trang trí hình tròn' },
    { type: 'item', title: 'H.13   Khối lập phương, khối hộp chữ nhật' },
    { type: 'item', title: 'H.14   Ghép hình' },
    { type: 'head', title: 'I. Đo lường' },
    { type: 'item', title: 'I.1   Mi-li-mét' },
    { type: 'item', title: 'I.2   Đổi đơn vị đo độ dài' },
    { type: 'item', title: 'I.3   Chu vi hình tam giác, hình tứ giác' },
    { type: 'item', title: 'I.4   Chu vi hình chữ nhật' },
    { type: 'item', title: 'I.5   Chu vi hình vuông' },
    { type: 'item', title: 'I.6   Diện tích của 1 hình' },
    { type: 'item', title: 'I.6   Đơn vị đo diện tích (Xăng- ti- mét vuông)' },
    { type: 'item', title: 'I.7   Diện tích hình chữ nhật' },
    { type: 'item', title: 'I.8   Diện tích hình vuông' },
    { type: 'item', title: 'I.9   Gam' },
    { type: 'item', title: 'I.10   Đổi đơn vị đo khối lượng' },
    { type: 'item', title: 'I.11   Mi-li-lít' },
    { type: 'item', title: 'I.12   Đổi đơn vị đo dung tích' },
    { type: 'item', title: 'I.13   Đơn vị đo nhiệt độ (oC)' },
    { type: 'item', title: 'I.14   Sử dụng dụng cụ đo' },
    { type: 'item', title: 'I.15   Ước lượng kết quả đo lường' },
    { type: 'item', title: 'I.16   Tính toán và đổi đơn vị đo' },
    { type: 'item', title: 'I.17   Bài toán thực tế về đo lường' },
    { type: 'item', title: 'I.18   Tháng - Năm' },
    { type: 'item', title: 'I.19   Giờ lẻ 5 phút' },
    { type: 'item', title: 'I.20   Giờ lẻ 1 phút' },
    { type: 'item', title: 'I.21   Bài toán về thời gian' },
    { type: 'item', title: 'I.22   Mệnh giá tiền Việt Nam' },
    { type: 'item', title: 'I.23   Bài toán liên quan đến tiền Việt Nam' },
    { type: 'head', title: 'K. Thống kê và xác suất' },
    { type: 'item', title: 'K.1   Thu thập, phân loại, sắp xếp các số liệu' },
    { type: 'item', title: 'K.2   Đọc bảng số liệu' },
    { type: 'item', title: 'K.3   Nhận xét bảng số liệu' },
    { type: 'item', title: 'K.4   Xác suất' }
]

module.exports = {
    dataFlatlist,
    listTest,
    dataGrade,
    dataGender,
    dataParent,
    dataProgramC1,
    dataProgramC2,
    dataProgramC3,
    dataSwipper,
    datalistProblemHierachy,
    datalistProblemHierachyExerice
}